using Android.App.Admin;
using Android.Content;
using Microsoft.Extensions.Logging;
using FleetHubAgent.Fleet;

namespace FleetHubAgent.Android.Policy;

/// <summary>
/// Whether this app holds Device Owner, and the powers it takes when it does.
///
/// **Everything that needs Device Owner asks here first, and degrades rather than throwing.**
/// That is the contract the rest of the policy work is built on, and it exists because the
/// failure it prevents is invisible: a sideloaded build with no Device Owner can still be told
/// to suspend an app or lock a screen, and the API answers with a SecurityException that an
/// executor turns into "executor error: ..." -- which reads, in the console, exactly like a
/// device that is broken. The honest answer is "this device is not fully managed", and it can
/// only be given by a check that happens before the call.
///
/// **Device Owner is a one-way door.** It can only be taken before any account is added to the
/// device, which in production means immediately after a factory reset, by scanning a
/// provisioning QR at the setup wizard. There is no API to grant it later and none to move it
/// to a different app. A wrong component name or a wrong signature checksum in that QR costs
/// another wipe, and on a device somebody uses, an accidental provision costs everything on
/// it. Nothing in this file, and nothing in this app, can start that flow -- the QR is
/// generated by the hub (hub/provisioning_web.py) and scanned by the setup wizard.
///
/// **What is deliberately NOT taken**, because a fleet agent should hold the narrowest set
/// that does its job: no camera or screenshot restrictions, no factory-reset block, no
/// certificate installation, no always-on VPN, no keyguard restrictions, and no account
/// management restrictions. Each is available to a Device Owner and each would be a change to
/// how the device behaves for the person holding it rather than a capability the console
/// needs. They are listed here so a later phase adds one on purpose rather than by reflex.
/// </summary>
public static class DeviceOwner
{
    /// <summary>Does this app hold Device Owner on this device?
    ///
    /// False is the ORDINARY answer, not an error: a sideloaded build, a device provisioned
    /// with an MDM that is not this one, and every device enrolled before this feature existed
    /// all read false and go on reporting telemetry exactly as before. Only the policy features
    /// are withheld.
    /// </summary>
    public static bool IsManaged(Context? context)
    {
        var dpm = Manager(context);
        try
        {
            return dpm is not null && context is not null
                   && dpm.IsDeviceOwnerApp(context.PackageName);
        }
        catch (Exception)
        {
            // A device with no device-policy service at all (some cut-down builds, and every
            // emulator image without the framework feature). Reading that as "not managed" is
            // both true and the safe direction: nothing is attempted.
            return false;
        }
    }

    /// <summary>The capability features this device can honestly claim (see
    /// hub/capabilities.py). Evaluated per heartbeat rather than once at startup, because
    /// `adb shell dpm set-device-owner` can grant this to a process that is already
    /// running -- which is the lab path, and the one where a stale answer would be most
    /// confusing.</summary>
    public static IReadOnlyList<string> Features(Context? context)
        => IsManaged(context) ? [AgentCapabilities.FeatureDeviceOwner] : [];

    /// <summary>
    /// Take the powers this agent wants and can hold today. Safe to call repeatedly -- it runs
    /// on every service start, because that is also the path a device takes after an OS update
    /// resets a setting, and there is nobody at the device to notice.
    ///
    /// **Only one power is taken here, and the rest wait for the phase that uses them.** A
    /// policy applied before anything reads it is a change to somebody's device that buys
    /// nothing, and it is the kind of thing that is never removed because nobody remembers what
    /// asked for it. Location's permission grant lands with the locate command; app suspension
    /// lands with app policy; lock and wipe land with theirs.
    /// </summary>
    public static void ApplyBaseline(Context? context, ILogger log)
    {
        if (!IsManaged(context)) return;
        var dpm = Manager(context);
        if (dpm is null || context is null) return;
        var admin = Component(context);

        // Stops the agent being force-stopped or its data cleared from the app info screen.
        // This is the one power worth taking on day one, because without it the whole feature
        // set is optional from the device's side: anybody holding the phone can end the service
        // from Settings, and the machine simply goes quiet in the console -- indistinguishable
        // from a flat battery or a device that left the building.
        //
        // It is NOT a fix for the OEM power-manager problem, and must not be read as one. Those
        // killers run inside the system and do not go through the user-control path this
        // blocks; this stops a PERSON, not Samsung's battery manager. The overnight survival
        // question is still open (roadmap #23).
        EnforceAutomaticTime(dpm, admin, log);

        if (!OperatingSystem.IsAndroidVersionAtLeast(30)) return;
        var package = context.PackageName;
        if (string.IsNullOrEmpty(package)) return;
        try
        {
            dpm.SetUserControlDisabledPackages(admin, [package]);
            log.LogInformation("Device Owner: user control of {Package} disabled", package);
        }
        catch (Exception e)
        {
            // Never fatal. A device that refuses this is still a managed device that reports
            // telemetry and takes commands; it is one where somebody can stop the agent by
            // hand. Worth a line in the log and nothing more.
            log.LogWarning("Device Owner: could not disable user control: {Msg}", e.Message);
        }
    }

    /// <summary>
    /// Take the device's clock away from the person holding it -- roadmap #23 phase E.
    ///
    /// **This is the power a curfew rests on.** Windows and budgets are evaluated on the
    /// device against its own local clock, which is the only way a phone with no signal at
    /// 22:00 still has a bedtime. That trust is only defensible if the clock is not a setting
    /// somebody can move: without this, "no TikTok after 22:00" is undone by walking into
    /// date and time settings and saying it is 09:00.
    ///
    /// It is the narrow version of the power, deliberately. The device takes its time from the
    /// network, as it would out of the box; nothing here SETS a time, and the time zone stays
    /// the device's own, because a fleet-imposed zone would put a traveller's curfew at the
    /// wrong hour for the person it is about.
    ///
    /// Applied on every service start rather than once, because an OS update can reset it and
    /// there is nobody at the device to notice.
    /// </summary>
    private static void EnforceAutomaticTime(DevicePolicyManager dpm, ComponentName admin,
        ILogger log)
    {
        try
        {
            if (OperatingSystem.IsAndroidVersionAtLeast(30))
            {
                dpm.SetAutoTimeEnabled(admin, true);
            }
            else
            {
#pragma warning disable CA1422 // the pre-30 spelling, reached only below 30
                // setAutoTimeRequired is the older, blunter form: it forbids manual time
                // rather than turning automatic time on. Same effect for this purpose, and it
                // is what a device below 30 has.
                dpm.SetAutoTimeRequired(admin, true);
#pragma warning restore CA1422
            }
            log.LogInformation("Device Owner: automatic time enforced");
        }
        catch (Exception e)
        {
            // Never fatal, and worth being explicit about what is lost: the device still
            // enforces its schedule, against a clock the user can move. The console cannot
            // see that from here, which is why this line exists.
            log.LogWarning("Device Owner: could not enforce automatic time, so a schedule on " +
                           "this device can be defeated by changing the clock: {Msg}", e.Message);
        }
    }

    /// <summary>
    /// Grant this app location on a fully managed device -- roadmap #23 phase B.
    ///
    /// **Declaring a dangerous permission in the manifest grants nothing**, and phase B shipped
    /// as though it did. Since API 23 the platform withholds ACCESS_FINE_LOCATION and
    /// ACCESS_COARSE_LOCATION until somebody says yes at runtime, and nothing in this app ever
    /// asked. The manifest looked complete, AndroidLocationReader checked the permission
    /// correctly, every workstation test passed, and every locate on every device would have
    /// answered "the location permission has not been granted on this device" -- a true
    /// sentence that reads, in the console, like a device somebody deliberately locked down
    /// rather than a feature that was never wired up. Nothing would have said otherwise until
    /// the hardware pass.
    ///
    /// **setPermissionGrantState is the only way to grant it with nobody at the device.** A
    /// managed phone is provisioned by QR and then put in a drawer or a van; there is no one to
    /// answer a dialog, and a permission dialog is the whole of the ordinary path. A Device
    /// Owner decides instead, the platform records the grant, and nothing appears on screen.
    /// An UNMANAGED device has a technician holding it, and MainActivity asks them.
    ///
    /// **Called from the locate rather than from <see cref="ApplyBaseline"/>**, which is the
    /// promise ApplyBaseline's own docstring makes: a power taken before anything reads it is a
    /// change to somebody's device that buys nothing and that nobody later remembers asking
    /// for. A fleet that never locates a device never grants itself location on one.
    ///
    /// **Both permissions, and the coarse one is not redundant.** The reader accepts either,
    /// because a device findable to the nearest block is most of the value of finding a lost
    /// phone, and from API 31 the platform models approximate location as a grant of its own
    /// rather than as a weaker form of the precise one.
    ///
    /// **ACCESS_BACKGROUND_LOCATION is not granted here, and could not be.** From Android 11
    /// the platform refuses to auto-grant it whatever a Device Owner says -- and this app does
    /// not request it at all, which is the older and more important half of that sentence.
    /// Background reach comes from promoting the foreground service for the length of one
    /// request. See AndroidLocationReader and the manifest.
    ///
    /// **A Device Owner's right to grant location is not unconditional, and the check is asked
    /// for rather than discovered by throwing.** From Android 12 location joins the
    /// sensors-related permissions, which a device owner may grant only if the provisioning
    /// flow did not opt out of that control with
    /// EXTRA_PROVISIONING_SENSORS_PERMISSION_GRANT_OPT_OUT. This hub's QR does not set that
    /// extra (hub/provisioning.py), so a device provisioned the intended way keeps the right --
    /// but a device provisioned by hand, or by an earlier tool, may not, and on a target SDK of
    /// 35 or later the platform answers that by THROWING rather than by returning false.
    /// canAdminGrantSensorsPermissions is the question asked directly, and asking it is what
    /// turns "executor error: SecurityException" into a log line naming what is wrong.
    ///
    /// Returns whether the platform accepted at least one grant. The caller re-asks
    /// CheckSelfPermission rather than trusting this, because "the admin was allowed to set
    /// it" and "this process now holds it" are different questions and only the second one
    /// decides whether a fix can be taken.
    /// </summary>
    public static bool GrantLocation(Context? context, ILogger log)
    {
        if (!IsManaged(context)) return false;
        var dpm = Manager(context);
        if (dpm is null || context is null) return false;
        var package = context.PackageName;
        if (string.IsNullOrEmpty(package)) return false;
        var admin = Component(context);

        // API 31+ only; below it there is no sensors restriction and nothing to ask about.
        if (OperatingSystem.IsAndroidVersionAtLeast(31))
        {
            try
            {
                if (!dpm.CanAdminGrantSensorsPermissions())
                {
                    // Recorded rather than attempted. The grant below would throw on a modern
                    // target SDK, and the resulting SecurityException carries none of this.
                    log.LogWarning("Device Owner: this device was provisioned without the " +
                                   "right to grant sensor permissions, so location must be " +
                                   "granted by hand on the agent's setup screen");
                    return false;
                }
            }
            catch (Exception e)
            {
                // The question itself failed, which says nothing about the answer. Fall
                // through and let the grant below report what the platform actually does.
                log.LogDebug("Device Owner: could not ask about sensor grants: {Msg}", e.Message);
            }
        }

        var accepted = false;
        foreach (var permission in new[]
                 {
                     global::Android.Manifest.Permission.AccessFineLocation,
                     global::Android.Manifest.Permission.AccessCoarseLocation,
                 })
        {
            try
            {
                if (dpm.SetPermissionGrantState(admin, package, permission,
                                                PermissionGrantState.Granted))
                {
                    accepted = true;
                }
                else
                {
                    // The API says no by returning false rather than by throwing, and a
                    // swallowed false here is the same invisible failure this whole method
                    // exists to end. A device can refuse: a permission policy set by another
                    // admin, or an OEM build that does not honour the call.
                    log.LogWarning("Device Owner: the platform would not grant {Permission}",
                        permission);
                }
            }
            catch (Exception e)
            {
                // Never fatal. The locate that called this goes on to ask the platform what it
                // actually holds, and answers "unavailable" with a reason if the answer is no.
                log.LogWarning("Device Owner: could not grant {Permission}: {Msg}",
                    permission, e.Message);
            }
        }

        if (accepted) log.LogInformation("Device Owner: location granted to {Package}", package);
        return accepted;
    }

    /// <summary>One line for the setup screen. Phrased for the person holding the device, who
    /// is usually the helpdesk technician provisioning it and needs to know whether the QR
    /// actually took -- the difference between "fully managed" and "installed like any other
    /// app" is invisible otherwise, and it is the difference between a device that can be
    /// located and locked and one that cannot.</summary>
    public static string Describe(Context? context)
        => IsManaged(context)
            ? "Fully managed (device owner)"
            : "Not fully managed -- installed as an ordinary app";

    /// <summary>This app's admin component, the name the provisioning QR must carry verbatim.
    ///
    /// Built from the receiver type rather than written as a string, so the QR generator and
    /// the device cannot disagree about it: the hub's copy is a setting an operator pastes in,
    /// and a mismatch there is not a failed install -- it is a device that has been factory
    /// reset and cannot finish provisioning, which costs a second wipe to discover.
    /// </summary>
    public static ComponentName Component(Context context)
        => new(context, Java.Lang.Class.FromType(typeof(FleetDeviceAdminReceiver)));

    private static DevicePolicyManager? Manager(Context? context)
        => context?.GetSystemService(Context.DevicePolicyService) as DevicePolicyManager;
}
