using Android.App.Admin;
using Android.Content;
using Microsoft.Extensions.Logging;
using FleetHubAgent.Fleet;

namespace FleetHubAgent.Android.Policy;

/// <summary>
/// Whether this app holds Device Owner, and the powers it takes when it does.
///
/// **Everything that needs Device Owner asks here first, and degrades rather than throwing.**
/// That is the contract the rest of the policy work is built on, and it exists because the
/// failure it prevents is invisible: a sideloaded build with no Device Owner can still be told
/// to suspend an app or lock a screen, and the API answers with a SecurityException that an
/// executor turns into "executor error: ..." -- which reads, in the console, exactly like a
/// device that is broken. The honest answer is "this device is not fully managed", and it can
/// only be given by a check that happens before the call.
///
/// **Device Owner is a one-way door.** It can only be taken before any account is added to the
/// device, which in production means immediately after a factory reset, by scanning a
/// provisioning QR at the setup wizard. There is no API to grant it later and none to move it
/// to a different app. A wrong component name or a wrong signature checksum in that QR costs
/// another wipe, and on a device somebody uses, an accidental provision costs everything on
/// it. Nothing in this file, and nothing in this app, can start that flow -- the QR is
/// generated by the hub (hub/provisioning_web.py) and scanned by the setup wizard.
///
/// **What is deliberately NOT taken**, because a fleet agent should hold the narrowest set
/// that does its job: no camera or screenshot restrictions, no factory-reset block, no
/// certificate installation, no always-on VPN, no keyguard restrictions, and no account
/// management restrictions. Each is available to a Device Owner and each would be a change to
/// how the device behaves for the person holding it rather than a capability the console
/// needs. They are listed here so a later phase adds one on purpose rather than by reflex.
/// </summary>
public static class DeviceOwner
{
    /// <summary>Does this app hold Device Owner on this device?
    ///
    /// False is the ORDINARY answer, not an error: a sideloaded build, a device provisioned
    /// with an MDM that is not this one, and every device enrolled before this feature existed
    /// all read false and go on reporting telemetry exactly as before. Only the policy features
    /// are withheld.
    /// </summary>
    public static bool IsManaged(Context? context)
    {
        var dpm = Manager(context);
        try
        {
            return dpm is not null && context is not null
                   && dpm.IsDeviceOwnerApp(context.PackageName);
        }
        catch (Exception)
        {
            // A device with no device-policy service at all (some cut-down builds, and every
            // emulator image without the framework feature). Reading that as "not managed" is
            // both true and the safe direction: nothing is attempted.
            return false;
        }
    }

    /// <summary>The capability features this device can honestly claim (see
    /// hub/capabilities.py). Evaluated per heartbeat rather than once at startup, because
    /// `adb shell dpm set-device-owner` can grant this to a process that is already
    /// running -- which is the lab path, and the one where a stale answer would be most
    /// confusing.</summary>
    public static IReadOnlyList<string> Features(Context? context)
        => IsManaged(context) ? [AgentCapabilities.FeatureDeviceOwner] : [];

    /// <summary>
    /// Take the powers this agent wants and can hold today. Safe to call repeatedly -- it runs
    /// on every service start, because that is also the path a device takes after an OS update
    /// resets a setting, and there is nobody at the device to notice.
    ///
    /// **Only one power is taken here, and the rest wait for the phase that uses them.** A
    /// policy applied before anything reads it is a change to somebody's device that buys
    /// nothing, and it is the kind of thing that is never removed because nobody remembers what
    /// asked for it. Location's permission grant lands with the locate command; app suspension
    /// lands with app policy; lock and wipe land with theirs.
    /// </summary>
    public static void ApplyBaseline(Context? context, ILogger log)
    {
        if (!IsManaged(context)) return;
        var dpm = Manager(context);
        if (dpm is null || context is null) return;
        var admin = Component(context);

        // Stops the agent being force-stopped or its data cleared from the app info screen.
        // This is the one power worth taking on day one, because without it the whole feature
        // set is optional from the device's side: anybody holding the phone can end the service
        // from Settings, and the machine simply goes quiet in the console -- indistinguishable
        // from a flat battery or a device that left the building.
        //
        // It is NOT a fix for the OEM power-manager problem, and must not be read as one. Those
        // killers run inside the system and do not go through the user-control path this
        // blocks; this stops a PERSON, not Samsung's battery manager. The overnight survival
        // question is still open (roadmap #23).
        if (!OperatingSystem.IsAndroidVersionAtLeast(30)) return;
        var package = context.PackageName;
        if (string.IsNullOrEmpty(package)) return;
        try
        {
            dpm.SetUserControlDisabledPackages(admin, [package]);
            log.LogInformation("Device Owner: user control of {Package} disabled", package);
        }
        catch (Exception e)
        {
            // Never fatal. A device that refuses this is still a managed device that reports
            // telemetry and takes commands; it is one where somebody can stop the agent by
            // hand. Worth a line in the log and nothing more.
            log.LogWarning("Device Owner: could not disable user control: {Msg}", e.Message);
        }
    }

    /// <summary>One line for the setup screen. Phrased for the person holding the device, who
    /// is usually the helpdesk technician provisioning it and needs to know whether the QR
    /// actually took -- the difference between "fully managed" and "installed like any other
    /// app" is invisible otherwise, and it is the difference between a device that can be
    /// located and locked and one that cannot.</summary>
    public static string Describe(Context? context)
        => IsManaged(context)
            ? "Fully managed (device owner)"
            : "Not fully managed -- installed as an ordinary app";

    /// <summary>This app's admin component, the name the provisioning QR must carry verbatim.
    ///
    /// Built from the receiver type rather than written as a string, so the QR generator and
    /// the device cannot disagree about it: the hub's copy is a setting an operator pastes in,
    /// and a mismatch there is not a failed install -- it is a device that has been factory
    /// reset and cannot finish provisioning, which costs a second wipe to discover.
    /// </summary>
    public static ComponentName Component(Context context)
        => new(context, Java.Lang.Class.FromType(typeof(FleetDeviceAdminReceiver)));

    private static DevicePolicyManager? Manager(Context? context)
        => context?.GetSystemService(Context.DevicePolicyService) as DevicePolicyManager;
}
